name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - pandas=1
  - pip:
    - mlflow<3,>=2.2
    - pyspark==3.3.0
    - scipy==1.7.1
    - azureml-mlflow
    - azureml-defaults==1.47.0
    - inference-schema[numpy-support]==1.5
    - joblib==1.0.1